version: "3.8"

services:
    math_32:
        image: rocker/verse
        container_name: math_32
        tty: true
        environment:
            USER: admin
            PASSWORD: password
        volumes:
            - .:/home/rstudio/lab
            - ./config:/home/admin/.config/rstudio/
        ports:
            - 8787:8787