```{r}
library(tidyverse)
library(moderndive)
library(infer)
```

```{r}
# load myth busters dataset
mythbusters_yawn
```

```{r}
# create a summary of the data set 
mythbusters_yawn %>% 
  group_by(group, yawn) %>% 
  summarize(count = n())
```

```{r}
# specify our variables
mythbusters_yawn %>% 
  specify(formula = yawn ~ group, success = "yes")
```

```{r}
# display the headers for the dataset
head(mythbusters_yawn)
```

```{r}
# condense the dataset
head(mythbusters_yawn) %>% 
  sample_n(size = 6, replace = TRUE)
```


```{r}
# generate replicates
mythbusters_yawn %>% 
  specify(formula = yawn ~ group, success = "yes") %>% 
  generate(reps = 1000, type = "bootstrap")
```

```{r}
# calculate the summary statistics
mythbusters_yawn %>% 
  specify(formula = yawn ~ group, success = "yes") %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "diff in props")
```

```{r}
# saving the output to a variable and displaying its values
bootstrap_distribution_yawning <- mythbusters_yawn %>% 
  specify(formula = yawn ~ group, success = "yes") %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "diff in props", order = c("seed", "control"))
bootstrap_distribution_yawning
```

```{r}
# graph the output
visualize(bootstrap_distribution_yawning)
```

```{r}
# calculate the confidence interval
bootstrap_distribution_yawning %>% 
  get_confidence_interval(type = "percentile", level = 0.95)
```

```{r}
# calculate the difference in props
mythbusters_yawn %>% 
  specify(formula = yawn ~ group, success = "yes") %>% 
  # generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "diff in props", order = c("seed", "control"))
```

```{r}
# calculate the confidence interval
bootstrap_distribution_yawning %>% 
  get_confidence_interval(type = "se", point_estimate = 0.0441176)
```

```{r}
# Compute the bootstrap distribution using infer workflow:
bootstrap_distribution <- bowl_sample_1 %>% 
  specify(response = color, success = "red") %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "prop")
```

```{r}
# summarize the dataset
bootstrap_distribution %>% 
  summarize(se = sd(stat))
```

```{r}
# compute the confidence interval based on 33 tactile
conf_ints <- tactile_prop_red %>% 
  rename(p_hat = prop_red) %>% 
  mutate(
    n = 50,
    SE = sqrt(p_hat * (1 - p_hat) / n),
    MoE = 1.96 * SE,
    lower_ci = p_hat - MoE,
    upper_ci = p_hat + MoE
  )
conf_ints
```
